// Code generated by "stringer -type=spinnerTyp"; DO NOT EDIT.

package pkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spinner01-1]
}

const _spinnerTyp_name = "Spinner01"

var _spinnerTyp_index = [...]uint8{0, 9}

func (i spinnerTyp) String() string {
	i -= 1
	if i >= spinnerTyp(len(_spinnerTyp_index)-1) {
		return "spinnerTyp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _spinnerTyp_name[_spinnerTyp_index[i]:_spinnerTyp_index[i+1]]
}
